# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Antonio Nascimento Lutfi
email: antonio.lutfi@gmail.com
description: Antonio Lutfi's online resume and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.antoniolutfi.com.br" # the base hostname & protocol for your site
twitter_username: 
github_username:  anlutfi
blog: blog.antoniolutfi.com.br

markdown: redcarpet
excerpt_separator: <!--more-->


# Build settings
markdown: kramdown

safe: true
lsi: false
